const questions = {
    randomFun: [
        "What's your favorite superhero?",
        "If you could have any superpower, what would it be?",
        "What's the weirdest food you've ever eaten?",
        "If you could travel anywhere in the world, where would you go?",
        "What's the funniest joke you know?",
        "If you were an animal, what animal would you be?",
        "What's your favorite holiday?",
        "What's the strangest thing you've ever seen?",
        "If you were a movie character, who would you be?",
        "What's the best compliment you've ever received?",
        "If you could live in any time period, which would it be?",
        "What's the best prank you've pulled?",
        "What's your most embarrassing moment?",
        "What's your hidden talent?",
        "If you could meet any celebrity, who would it be?",
        "What's your favorite ice cream flavor?",
        "What's your favorite childhood memory?",
        "What's the best gift you've ever received?",
        "If you were a fruit, what fruit would you be?",
        "What's the coolest thing you've ever done?",
        "If you could only eat one food for the rest of your life, what would it be?",
        "What's your dream job?",
        "If you were a ghost, where would you haunt?",
        "What's the best movie you've ever seen?",
        "If you could change your name, what would it be?"
    ],
    math: [
        "What is 8 x 9?",
        "What is the square root of 144?",
        "Solve for x: 2x + 3 = 11",
        "What is the value of pi up to 3 decimal places?",
        "What is the derivative of x^2?",
        "Solve for y: 3y - 4 = 11",
        "What is 15% of 200?",
        "What is the area of a circle with radius 5?",
        "Solve for x: x^2 - 4x + 4 = 0",
        "What is the cosine of 60 degrees?",
        "Simplify: (3x^2 + 2x) - (x^2 + x)",
        "What is the volume of a cube with side length 3?",
        "What is 12 / 3 + 4 * 2?",
        "Solve for z: 5z - 3 = 2z + 12",
        "What is 9 squared?",
        "What is the Pythagorean theorem?",
        "What is the integral of 2x?",
        "What is the sum of the angles in a triangle?",
        "What is 7 factorial?",
        "What is the greatest common divisor of 24 and 36?",
        "What is the least common multiple of 6 and 8?",
        "What is 7% of 500?",
        "Solve: 2x - 4 = 6",
        "What is the standard deviation of the set {2, 4, 6, 8}?",
        "What is the median of {1, 3, 3, 6, 7, 8, 9}?"
    ],
    coding: [
        "What does HTML stand for?",
        "What is a closure in JavaScript?",
        "What is a REST API?",
        "What is the difference between frontend and backend?",
        "What is the purpose of a database index?",
        "What is a class in object-oriented programming?",
        "What is recursion?",
        "What is polymorphism in OOP?",
        "Explain how Git works.",
        "What is the difference between var, let, and const in JavaScript?",
        "What is Big O notation?",
        "What is the use of Docker in DevOps?",
        "What is an HTTP request?",
        "What is a JOIN in SQL?",
        "What is a NoSQL database?",
        "What is the use of CSS Flexbox?",
        "What is responsive design?",
        "Explain the use of React.js hooks.",
        "What is the purpose of middleware in backend frameworks?",
        "What is an ORM in web development?",
        "What is functional programming?",
        "What is the use of npm?",
        "What is the difference between synchronous and asynchronous code?",
        "Explain the concept of event bubbling in JavaScript.",
        "What is RESTful architecture?"
    ],
    techTrends: [
        "What is blockchain technology?",
        "What is the Internet of Things (IoT)?",
        "What is the 5G network?",
        "What is quantum computing?",
        "What are microservices?",
        "What is the metaverse?",
        "What is the use of AI in healthcare?",
        "What is cloud computing?",
        "What is edge computing?",
        "What is a chatbot?",
        "What is augmented reality?",
        "What is virtual reality?",
        "What is serverless architecture?",
        "What is artificial general intelligence?",
        "What is the impact of 5G on smart cities?",
        "What is a digital twin?",
        "What is autonomous driving?",
        "What is cybersecurity?",
        "What are nanobots?",
        "What is a smart contract?",
        "What is DevOps?",
        "What is the importance of data privacy?",
        "What is a hybrid cloud?",
        "What is a software-defined network (SDN)?",
        "What is AI bias?"
    ],
    ai: [
        "What is machine learning?",
        "What is deep learning?",
        "What is a neural network?",
        "What is natural language processing?",
        "What is supervised learning?",
        "What is unsupervised learning?",
        "What is reinforcement learning?",
        "What is a convolutional neural network (CNN)?",
        "What is generative adversarial network (GAN)?",
        "What is transfer learning?",
        "What is a decision tree?",
        "What is overfitting?",
        "What is underfitting?",
        "What is backpropagation?",
        "What is the Turing test?",
        "What is a chatbot in AI?",
        "What is a recommendation system?",
        "What is AI ethics?",
        "What is a support vector machine (SVM)?",
        "What is a random forest?",
        "What is the difference between AI and machine learning?",
        "What is the role of AI in automation?",
        "What is bias in AI models?",
        "What is a language model in AI?",
        "What is predictive analytics?"
    ],
    pizzas: [
        "What is your favorite pizza topping?",
        "Which city has the best pizza: New York or Chicago?",
        "What is the best crust type: thin, thick, or stuffed?",
        "What is the best cheese for pizza?",
        "What is the perfect pizza sauce?",
        "What is the best pizza place you've been to?",
        "Is pineapple on pizza acceptable?",
        "What is your favorite pizza style: Neapolitan, Sicilian, or Detroit?",
        "What is the weirdest pizza topping you've tried?",
        "How many slices of pizza can you eat in one sitting?",
        "What is your favorite frozen pizza brand?",
        "Do you prefer a brick oven or a gas oven pizza?",
        "What is the best side dish with pizza?",
        "Do you fold your pizza slice when you eat it?",
        "What is the best beverage to have with pizza?",
        "What is your favorite homemade pizza topping combo?",
        "Which pizza chain is your go-to: Domino's, Pizza Hut, or Papa John's?",
        "What is the best pizza shape: round or square?",
        "What is your opinion on vegan pizza?",
        "What is the best dipping sauce for pizza?",
        "What is the best pizza for breakfast?",
        "Which country makes the best pizza outside of Italy?",
        "Do you like pizza with extra cheese?",
        "What’s the best pizza topping combo?",
        "Is pizza better with or without red pepper flakes?"
    ]
};

function showQuestion(category) {
    const randomIndex = Math.floor(Math.random() * questions[category].length);
    document.getElementById("question-text").innerText = questions[category][randomIndex];
    document.getElementById("question-box").classList.remove("hidden");
}
